Manual
Comets3357/RobotCode-3005 pull request #12
Opened 2023-08-17 18:57 UTC by SuperJavierWorld

Code for the joysticks

2023-08-17 19:04 UTC, hnsorens requested changes
Can you create a set percent function for each subsystem. The point of setting a manual power is not to set the position. We need set percent functions in each subsystem that does not have them so we can set the percent and not the position. The joystick value should never be put into a SetPosition function because position is moving the motor to a specific encoder position which is not what manual is supposed to do. manual is supposed to use the joysticks to control the subsystem by percent. Let me know if you have any questions.

2023-08-17 22:22 UTC, bennyjjumpin approved these changes
all variable names should start with lowercase letters.

2023-08-17 22:31 UTC, bennyjjumpin approved these changes
👍

2023-08-18 13:29 UTC, hnsorens approved these changes

2023-08-18 13:29 UTC, merged